openapi: "3.0.3"

info: 
  title: "Shop Review API"
  version: "1.0.0"

paths:
  "/shop/{shopId}/reviews": 
    parameters: 
      - name: shopId
        in: path
        required: true
        schema: {type: string}

    get: 
      summary: "Get shop reviews"
      tags: ["reviews"]
      responses: 
        "200":
          description: "Success Operation"
    post:
      summary: "Create reviews"
      tags: ["reviews"]
      responses: 
        "201":
          description: "Success Operation"

tags: 
  - name: reviews
    description: "Shop review opperation"